// Code generated by "stringer -type=Size"; DO NOT EDIT.

package patterns

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Small-0]
	_ = x[Medium-1]
	_ = x[Large-2]
}

const _Size_name = "SmallMediumLarge"

var _Size_index = [...]uint8{0, 5, 11, 16}

func (i Size) String() string {
	if i < 0 || i >= Size(len(_Size_index)-1) {
		return "Size(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Size_name[_Size_index[i]:_Size_index[i+1]]
}
